### ISSUE TITLE
JSON -> EDN with --keywordize produces invalid EDN when keys have spaces

### ISSUE THREAD

**Issue by fiddlerwoaroof** [borkdude/jet#10]
If you pass the `--keywordize` option, converting json to edn can produce invalid EDN:

```
% echo '{"a b": "c"}' | jet --from json --keywordize --to edn --pretty
{:a b "c"}
% echo '{"a b": "c"}' | jet --from json --keywordize --to edn --pretty | jet --from edn --to json
Exception in thread "main" java.lang.RuntimeException: Map literal must contain an even number of forms
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:682)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.lang.EdnReader.readString(EdnReader.java:67)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at jet.main$_main.invokeStatic(main.clj:51)
	at jet.main$_main.doInvoke(main.clj:44)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at jet.main.main(Unknown Source)
```

I'm not sure what the right solution here is: the strategies that occur to me are preserving json keys as strings if they contain invalid characters for keywords or applying some kind of deterministic transformation to the json keys (e.g. `" "` -> `"-"` and `"-"` -> `"--"`) to turn them into valid edn keywords.

**Comment by borkdude** [comment]
Maybe this is good to discuss at https://github.com/dakrone/cheshire since everyone who uses that library will run into the same issue?

**Comment by fiddlerwoaroof** [comment]
It looks like someoone brought it up: https://github.com/dakrone/cheshire/issues/129

It's not a problem for a library like cheshire because you can create a keyword with a space in it, the problem is that you can't serialize and deserialize such keywords reliably:

```
user=> {(keyword "a b") 2}
{:a b 2}
user=> ({(keyword "a b") 2} (keyword "a b"))
2
```

**Comment by fiddlerwoaroof** [comment]
I just noticed that cheshire's json decoder can be passed a function that is used to transform the keys: https://github.com/dakrone/cheshire#decoding

```
;; parse some json and munge keywords with a custom function
(parse-string "{\"foo\":\"bar\"}" (fn [k] (keyword (.toUpperCase k))))
```

**Comment by borkdude** [comment]
@fiddlerwoaroof There are a couple of options:
- don't use keys with spaces in them
- don't use the `--keywordize` option and work with string keys
- an extension to the query language using `rename-keys`:

```
echo '{"foo bar": 1}' | lein jet --from json --to json --query '(rename-keys {"foo bar" "foo-bar"})'
{"foo-bar":1}
```
This JSON you can feed into jet once again to get EDN without keys with spaces.

- implement an optional mode for the `--keywordize` option, something like:

```
--keywordize '{:hyphenize-spaces true}'
```

**Comment by fiddlerwoaroof** [comment]
My concern is that if a tool like this is used in scripts, its defaults shouldn’t be dangerous: the current behavior of keywordize can cause two issues: one it can produce map literals with an invalid number of sub-expressions. But, worse, it can produce map literals that can be read back in wrong: if I have an even number of spaces, I will get spurious key-value pairs and possibly associate many of  the succeeding values with the wrong keys.

**Comment by borkdude** [comment]
@fiddlerwoaroof FWIW `--keywordize` is not the default.

**Comment by fiddlerwoaroof** [comment]
As far as I’m concerned, this behavior of keywordize means I can’t really use jet for shell scripts that process arbitrary data because  of the risk of data corruption: it seems to me that a cli tool shouldn’t make it easy to generate invalid output. 

That being said, I think the idea of allowing keywordize to take an optional argument that specifies how to transform the keyword name is a sufficient solution for my use cases.

**Comment by borkdude** [comment]
@fiddlerwoaroof I'm repeating myself, but you can use string keys if that is a concern. You don't have to use `--keywordize`.  I deal with data sources in my own projects where I don't use keywordize for similar reasons. What the best solution is, depends on the context of your data.

**Comment by borkdude** [comment]
Using the new query language (still experimental, subject to change), you can now do something like:

```
$ echo '{"foo bar": 1}' | jet --from json --to edn --query '{:foo_bar "foo bar"}'
{:foo_bar 1}
```

**Comment by borkdude** [comment]
@fiddlerwoaroof I might have a solution coming up where I let users pass in a custom key-fn that will be interpreted by https://github.com/borkdude/sci. This way you can do whatever you want.

**Comment by borkdude** [comment]
@fiddlerwoaroof Update:

A linux binary: https://565-197630288-gh.circle-artifacts.com/0/release/jet-0.0.10-SNAPSHOT-linux-amd64.zip
A mac binary: https://564-197630288-gh.circle-artifacts.com/0/release/jet-0.0.10-SNAPSHOT-macos-amd64.zip

This is now possible:

```
$ echo '{"my key": 1}' | jet --from json --keywordize '(fn [k] (-> (str/replace k " " "_") keyword))'
{:my_key 1}
```

It would be appreciated if you could experiment with this and see if this would solve your issue.

**Comment by fiddlerwoaroof** [comment]
I think this will solve my issue.

**Comment by borkdude** [comment]
This is released in v0.0.10. Please report back in a different issue if you find problems.

**Comment by behrica** [comment]
@borkdude  Can we reopen this ?
```
(read-string "{`:hello-world` 1}")

```
-> {:hello-world 1}
So END can have keywords with space in it.

**Comment by behrica** [comment]
So the --keyowrdize shold in my view just do this, and could teh produce valid EDN, even on keywords with spaces

```
(class (first (keys (read-string "{`:hello-world` 1}"))))
clojure.lang.Keyword
```
