### ISSUE TITLE
Perhaps sort would be a useful addition?

### ISSUE THREAD

**Issue by holyjak** [borkdude/jet#102]
I _think_ that adding `sort` (and `sort-by`) might be useful additions, if it is low-effort. 

My use case: check what aliases are avail. in Practicalli's deps.edn: `cat deps.edn | jet -q ':aliases keys'`

**Comment by borkdude** [comment]
Feel free to add.
You can also just use the `-f` option:

```
cat deps.edn | jet -f '#(-> % :aliases keys sort)'
```

**Comment by holyjak** [comment]
Ah, cool, I have not noticed `-f`!
