### ISSUE TITLE
Feature request: "raw" output flag

### ISSUE THREAD

**Issue by pieterbreed** [borkdude/jet#107]
This is a request to implement a the `-r` flag from `jq`. This flag allows for printing a string value from a query or fn, without wrapping in quotes and doing character escaping.

From jq manual:

- `--raw-output` / `-r`:
With this option, if the filter's result is a string then it will be written directly to standard output rather than being formatted as a JSON string with quotes. This can be useful for making jq filters talk to non-JSON-based systems.

I recently had to do this: `$ <something-producing-edn> | jet -q ':some-field' | jq -r` If `jet` had the -r flag, jq would not have been required here.

**Comment by borkdude** [comment]
Documented here: https://github.com/borkdude/jet#raw-output

**Comment by borkdude** [comment]
Fixed
