### ISSUE TITLE
Feature request: support M1 architecture

### ISSUE THREAD

**Issue by cesarolea** [borkdude/jet#108]
**Is your feature request related to a problem? Please describe.**

This is a feature request to support M1 architecture.

Describe the solution you'd like
Please add a release for arm64.

Describe alternatives you've considered
I've considered using it from the JVM and it should work, but the JVM startup time makes it significantly slower overall.

Additional context
On an M1 mac.

**Comment by borkdude** [comment]
@cesarolea I see something in cirrus now:

https://cirrus-ci.com/github/borkdude/jet

It says: No tasks were found for the build. Either only_if expressions excluded all of the tasks and/or Starlark script did not generate any tasks.

**Comment by borkdude** [comment]
I think the task should probably not be indented

**Comment by cesarolea** [comment]
I submitted another PR that fixes the indentation issue. Sorry about that.

**Comment by borkdude** [comment]
No worries! Can you rebase this commit on master though, so I can merge it?

**Comment by borkdude** [comment]
Done. Thanks!

**Comment by borkdude** [comment]
Now available as 0.2.18
