### ISSUE TITLE
`install` script does not work

### ISSUE THREAD

**Issue by emerson-matos** [borkdude/jet#126]
I'm trying to install jet as described in the [README.md#Quickstart](https://github.com/borkdude/jet/blame/master/README.md#L12), but the bash script isn't working, I don't know if I'm missing something

steps:
```sh
$ sudo bash <(curl -s https://raw.githubusercontent.com/borkdude/jet/master/install)
bash: /proc/self/fd/13: file or directory nonexistent
$ uname -s
Linux
$ echo $SHELL
/usr/bin/zsh
```

After some research I reached this [post](https://askubuntu.com/questions/1086617/dev-fd-63-no-such-file-or-directory), and I have tried another way

```sh
$ sudo bash < <(curl -s https://raw.githubusercontent.com/borkdude/jet/master/install)
Downloading https://github.com/borkdude/jet/releases/download/v0.4.23/jet-0.4.23-linux-amd64.tar.gz.
Successfully installed jet in /usr/local/bin.
```

**Comment by borkdude** [comment]
So the solution is to update the docs, right?

**Comment by borkdude** [comment]
Done
