### ISSUE TITLE
Possible cljs library usage?

### ISSUE THREAD

**Issue by riotrah** [borkdude/jet#133]
Per [this Calva issue](https://github.com/BetterThanTomorrow/calva/issues/2222#issuecomment-1591964322), how feasible do you think it might be to use `jet` as a cljs lib for Calva? 

I haven't checked the source, but I know that emacs/vim "integrations" just pipe in/out to the binary, so there doesn't appear to be any precedent this way, but wondering if you had any insight.

**Comment by borkdude** [comment]
I replied on the Calva issue. Since this is not a CLJS project, I don't think it makes sense for this project.
