### ISSUE TITLE
--keywordize fn not called when input is yaml

### ISSUE THREAD

**Issue by evanlouie** [borkdude/jet#134]
`-k`/`--keywordize` flag doesn't make use of key-fn when the input is YAML:

```sh
echo "foo_bar: baz" | jet -i yaml -k '#(keyword (str/replace % "_" "-"))'
{:foo_bar "baz"}
```

If I convert to JSON first, it works:

```sh
echo "foo_bar: baz" | jet -i yaml -o json | jet -i json -k '#(keyword (str/replace % "_" "-"))' 
{:foo-bar "baz"}
```

Jet version:

```sh
jet --version
0.5.25
```

**Comment by borkdude** [comment]
PR welcome. Not sure if clj-yaml supports a key-fn but if it does, it should not be that hard probably.
