### ISSUE TITLE
use jet from nix

### ISSUE THREAD

**Issue by slimslenderslacks** [borkdude/jet#146]
It would be nice to add jet to `<nixpkgs>` or even to just have a flake in this repo so that we can build jet into default dev environments using tools like home-manager.

**Comment by borkdude** [comment]
I'm fine with this as long as someone else provides the PR. There may already be someone maintaining this somewhere.

**Comment by slimslenderslacks** [comment]
Starting a draft PR here:  https://github.com/borkdude/jet/pull/147 - I'll ask in clojurians slack whether there's anyone already maintaining this somewhere.

**Comment by jlesquembre** [comment]
jet is already on nixpkgs: `nix run github:NixOS/nixpkgs/nixos-unstable#jet -- --help`

It could make sense to add a flake if you want to run the latest version from master with nix.

In that case, I think #147  can be simplified with some upcoming changes I have on mind for `clj-nix`. In a couple of weeks I could work on that, if you don't mind the wait. 
If you want to add a flake to the project, I'm ok maintaining it. To automate the boring parts, it would be nice to add a CI job to re-generate the `clj-nix` lock file after an update to the clojure dependencies.

**Comment by slimslenderslacks** [comment]
Oh! Thanks @jlesquembre - to be honest, this is all I would really want so I think maybe I'll close this issue.  I'll leave around the branch from #147 if you're interested in using it to test some clj-nix changes.  But I'll close this PR just to clean up. 

Thanks for adding jet to nixpkgs - I have the hardest time finding things there :)

**Comment by slimslenderslacks** [comment]
Closing
