### ISSUE TITLE
Conversion from json to edn without keywordize should produce string keys

### ISSUE THREAD

**Issue by jetmind** [borkdude/jet#2]
Hi! Thanks for the nice useful command line utility!

I would like to propose a couple of improvements.

Example from the docs produces symbol keys which is really inconvenient. You can't even copy & paste it to use in code/repl without introducing quoting.

```
$ echo '{"a": 1}' | jet --from json --to edn --keywordize false
{a 1}
```

I'd say it should output string keys, i.e. `{"a" 1}`.

Also it would be nice if `keywordize` was `true` by default since edn maps usually use keywords as keys.

What do you think about these?

**Comment by borkdude** [comment]
@jetmind Hi, this is definitely a bug. Which platform are you using to run jet? I'll fix it and will provide you with a new test version.

**Comment by jetmind** [comment]
@borkdude I'm using macOS 10.14.5, installed `jet` from brew

**Comment by borkdude** [comment]
@jetmind Here is a new linux version: https://43-197630288-gh.circle-artifacts.com/0/release/jet-0.0.2-SNAPSHOT-linux-amd64.zip
And a macOS version: https://41-197630288-gh.circle-artifacts.com/0/release/jet-0.0.2-SNAPSHOT-macos-amd64.zip

As for outputting keywords: I think it's best if this behaves like parsing functions people are already used to, e.g. `js->clj` in ClojureScript, where keywordizing also defaults to false.

**Comment by borkdude** [comment]
@jetmind Version 0.0.2 released to brew.
