### ISSUE TITLE
Support multiline "streams" of data?

### ISSUE THREAD

**Issue by justone** [borkdude/jet#32]
I have a use-case that I would like to use jet for. I have a file that has one edn form per line:

```
$ cat lines.edn 
{:bar something, :foo 63}
{:bar something, :foo 94}
{:bar something, :foo 19}
```

I would like to have a file with each line transformed into JSON, like this:

```
{"bar":"something","foo":63}
{"bar":"something","foo":94}
{"bar":"something","foo":19}
```

However, as of now, jet only handles the first form in the file:

```
$ cat lines.edn | jet --to json
{"bar":"something","foo":63}
```

What do you think of supporting multiple forms?

**Comment by borkdude** [comment]
@justone If I'm correct then all jet has to do to support this is wrap the input in an implicit array doseq + println on the output? Do you have a suggestion for the names of these flags?

**Comment by borkdude** [comment]
@justone Something I'm thinking about for babashka: introduce a `bb/*raw-in*` variable that just gives you the raw input string, so you can do whatever, e.g. wrap the input in a vector:

```
$ echo 'hello there' | lein bb '(format "[%s]" *raw-in*)'
"[hello there\n]"
```
That would probably be enough to solve this problem for you?

**Comment by borkdude** [comment]
@justone This is a Mac binary that includes this variable:

https://441-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.9-SNAPSHOT-macos-amd64.zip

Here's also a linux one: 

https://440-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.9-SNAPSHOT-linux-amd64.zip

**Comment by borkdude** [comment]
@justone Note that I wanted to support that option anyway, so if that's not sufficient for this use case, I'm still considering other solutions like a flag or two.

**Comment by justone** [comment]
I think having the entire raw input string would be useful. The downside is that bb needs to read in all of STDIN before it can start processing. I have some pretty large datasets and it would be cool to be able to be lazy about the processing.

Something like this, where each line is an edn form with a `:name` field:
```
$ cat 800-mb-file.edn | bb -n '(:name *in*)`
name1
name2
...
```
I'm inspired by the perl one-liners of old and using the [-n](https://perldoc.perl.org/perlrun.html#*-n*) flag, which wrapped your expression in a loop.

If it was lazy, it could also go in a pipeline after a process that is emitting one edn form per line:
```
$ ./process-that-emits-edn-every second | bb -n '(:status *in*)`
```

A few months ago, I started writing my own edn to json converter and [this code](https://github.com/app-sauce/edn2json/blob/initial/src/app/main.clj#L10-L17) enabled it to be stream aware.

**Comment by borkdude** [comment]
As discussed on slack, it's useful to have a streaming mode where the tool (both jet and bb) process one EDN value after another, until the stream is closed. To be explicit about this, we can introduce a `--stream` flag.

**Comment by borkdude** [comment]
@justone You can test the new jet with streaming support here:

https://498-197630288-gh.circle-artifacts.com/0/release/jet-0.0.8-SNAPSHOT-linux-amd64.zip

The old unit tests still pass so that's good. I have yet to write unit tests for these.

TODO: 

- [ ] unit tests

**Comment by justone** [comment]
This is amazing. Streaming works very well.
```
$ cat | jet --to json --from edn | jet --from json --to edn --keywordize | bb --stream '(:ts *in*)'
{:ts 123}
123
{:ts 123}
123
```
