### ISSUE TITLE
Support XML?

### ISSUE THREAD

**Issue by stathissideris** [borkdude/jet#35]
I know it's out of fashion, but maybe supporting XML would be interesting in coms contexts. There is of course the question of whether you'd convert it to hiccup-style structures or [data.xml](https://github.com/clojure/data.xml)-style.

**Comment by borkdude** [comment]
@stathissideris Feel free to elaborate and give some detailed examples of in- and outputs. Is this serving a real use case you have personally?

**Comment by borkdude** [comment]
I'd rather add XML support to babashka, this gives more flexibility of dealing with XML.

**Comment by aadrian** [comment]
@borkdude everybody would rather work with EDN instead of XML. Unfortunately XML is still present everywhere. Usually what many do is convert XML to JSON, but this looses allot of information that JSON can't handle, but EDN could.

**Comment by borkdude** [comment]
@aadrian The question is, how to support the `--query` or `--func` option on this? What kind of EDN does it turn into? You would have to give me some ideas before any work will be done on this.

**Comment by aadrian** [comment]
@borkdude you are right, more details are needed before considering such a feature.


> how to support the --query or --func option on this?

From the documentation, it seems `--query` operates on EDN, not on JSON https://github.com/borkdude/jet/blob/master/doc/query.md  so the behavior would be the same - would not operate on XML either I guess.

If "queries" on XML would be implemented, I guess XPath would be the mostly used.

Regarding `--func` : I haven't used it yet, so at the moment I'm not 100% sure how could be improved for XML.


> What kind of EDN does it turn into?

At the **simplest level**, would operate just like the JSON converter, but it could do more, e.g. to preserve more from the original content:
 - comments :) 
 - name spaces
 - CDATA handling
 - simple schema if present - e.g. for some of the built in simple schema types

Of course there are more possible improvements, but the above are elements that I usually take care almost all the time when working with XML.

**Comment by borkdude** [comment]
`--func` is just a function instead of a query over the input, just ordinary Clojure.
