### ISSUE TITLE
Add --help Option

### ISSUE THREAD

**Issue by defndaines** [borkdude/jet#41]
Great stuff.

If possible, can you add a `--help` option that will output the "Usage" section from the README?

For background, I'd installed via homebrew a while ago, but didn't actually use it until yesterday. I first tried to see what would happen if I just typed `jet` or `jet --help`, but it seems that it dropped it into interactive mode, so had to visit the website to check how to use. Would be nice to have the options handy right at the command line.

Thanks!

**Comment by borkdude** [comment]
@defndaines Good idea, I'm surprised I haven't done that yet. If you're interested in making a PR for this, that's also fine with me.
