### ISSUE TITLE
Add HTML -> EDN and EDN -> HTML transformations

### ISSUE THREAD

**Issue by borkdude** [borkdude/jet#49]
Libraries to consider:

- https://github.com/weavejester/hiccup, EDN -> HTML
- https://github.com/weavejester/hiccup/wiki/Converting-html-to-hiccup, HTML -> EDN

**Comment by borkdude** [comment]
In the hiccup branch, this works:

``` clojure
$ ./jet --from html <<< '<p><span>hello</span></p>'
[:p {} [:span {} "hello"]]

$ ./jet --to html <<< '[:p [:span "hello"]]'
<p><span>hello</span></p>
```

Question: should we make a distinction between the hiccup and hickory format?

**Comment by simon-brooke** [comment]
That sounds eminently sensible and almost a no-brainer; XML is, after all, only a stupidly prolix syntax for writing s-expressions. I'd stick with Hiccup format, unless there's a strong reason not to; but I'd also wish that the solution was generalised to any XML, rather than HTML specifically.

**Comment by borkdude** [comment]
New tool around HTML conversion and templating: https://github.com/retrogradeorbit/bootleg
Would be good to check what this tool does and what makes sense for jet to support.
