### ISSUE TITLE
Add CSV input/output

### ISSUE THREAD

**Issue by plexus** [borkdude/jet#52]
CSV is still a very common format, and it would be great to be able to easily feed a CSV file into `bb` for instance.

Unfortunately it's not terribly well standardized when it comes to quoting, and line and cell separators, and there might have to be some detection of a Byte Order Mark at the start.

`clojure/data.csv` would be the obvious choice, using its defaults for a `csv` format, and maybe also adding a `tsv` format with commas instead of tabs.

**Comment by borkdude** [comment]
@plexus PR welcome :)

**Comment by plexus** [comment]
Good to know!

**Comment by borkdude** [comment]
@plexus Follow up issue: https://github.com/borkdude/babashka/issues/95

**Comment by tobias-hammerschmidt** [comment]
@borkdude Are there any plans for merging the branch csv-support into master? I'm keen on using this feature :wink:

**Comment by borkdude** [comment]
@tobias-hammerschmidt Instead of adopting CSV in jet, we have decided to adopt clojure.data.csv into babashka instead. This gives you all the flexibility of working with this library without us having to wrap all the options behind command line arguments.
