### ISSUE TITLE
Consider YAML

### ISSUE THREAD

**Issue by borkdude** [borkdude/jet#54]

**Comment by iku000888** [comment]
Is there rationale to not support this @borkdude ? Sounds like a very useful feature

**Comment by borkdude** [comment]
@iku000888 The reason was mostly that its now support in babashka.

**Comment by iku000888** [comment]
@borkdude Thanks!
Will add link for prosperity https://github.com/borkdude/babashka/blob/023a02777274ac2f027d2914373ddc846aa1127e/test-resources/lib_tests/clj_yaml/core_test.clj
