### ISSUE TITLE
xml support?

### ISSUE THREAD

**Issue by rlhk** [borkdude/jet#67]
Hi is there a plan to support xml apart from json, edn, transit?
Or should I use Babashka instead?

Thanks.

**Comment by borkdude** [comment]
I have played around with xml conversations, but there are multiple representations in EDN (hiccup, hickory, etc). I think using babashka for this is more flexible.

**Comment by rlhk** [comment]
I figured out a satisfactory solution that might be helpful to others. So recording here.

My use case is to modify Xcode .plist files, which is in xml format. One good solution is to use the API of Xcode's CLI tool `PlistBuddy` from Babashka. That way one could write simple bb code to manipulate .plist files with XML validity gauranteed.

Info: https://fgimian.github.io/blog/2015/06/27/a-simple-plistbuddy-tutorial/
