### ISSUE TITLE
Sort keys in a map

### ISSUE THREAD

**Issue by agzam** [borkdude/jet#73]
I'm sorry, I can't figure this out. If you give me some pointers how to do this, I will send a PR for documentation update. I'm trying this and it's not working:

```
echo '{:b 2 :c 3 :a 1}' | jet --query '(into (sorted-map) #jet/lit)'
```

I'm sure at least a few people would find this functionality useful. Thanks!

**Comment by agzam** [comment]
Well, where `jet` cannot fly, `babashka` can plow through:

```
echo '{:b 2 :c 3 :a 1}' | bb '(into (sorted-map) *input*)'
```

But I'm still curious, if you can do this with jet

**Comment by borkdude** [comment]
`sorted-map` simply isn't available in the query language. I'm considering of just adding `-e` to jet so you can do the same as with `bb` in your last comment, since the query language is a bit weird sometimes.

**Comment by agzam** [comment]
Alright. That sounds exciting. Thank you for building such amazing set of tools. Everyone loves jet and everyone loves babashka. On that note I am going to close this issue.

**Comment by aviflax** [comment]
Just in case anyone else stumbles across this… now that `jet` has the `--function | -f` option, one can do something like this:

```clojure
echo '{:b 2 :c 3 :a 1}' | jet -f '#(into (sorted-map) %)'
```

And here’s what I came up with to do the same but recursively:

```clojure
echo '{:b 2 :c 3 :a 1 :q {:z 4 :y 6 :x 5}}' | jet -f '(fn [v] (clojure.walk/postwalk #(if (map? %) (into (sorted-map) %) %) v))'
