### ISSUE TITLE
Extension to YAML

### ISSUE THREAD

**Issue by davidpham87** [borkdude/jet#74]
Hello,

I think babashka supports yaml now, do you think it would make sense to extend the format to YAML? It might be useful for everyone working with k8s or ansible.

Best regards,
David

**Comment by borkdude** [comment]
@davidpham87 Why not just use babashka then?

**Comment by davidpham87** [comment]
This is what I did, I have my own script doing it. I thought it would be cool for jet to have this simple extension. I am crurently trying to write a pull request, not sure I managed.

**Comment by borkdude** [comment]
@davidpham87 Let's leave this issue open for feedback over the longer term.

**Comment by borkdude** [comment]
I've had more people ask for this and maybe it's about time we added support for YAML. If anyone is up for that, PR welcome.

**Comment by qdzo** [comment]
Jet is great tool. Thanks!
I always use it from emacs to convert my buffers.
And I also has struggle in that it does not have yaml. I know that - this is possible via babashka - but one tool for conversion is much better. 
It would be cool if this feature will have future.

**Comment by borkdude** [comment]
@qdzo Would you convert YAML to EDN? 

Is anyone in this thread open to working on a PR?

**Comment by qdzo** [comment]
50% yaml -> edn 
and 
50% yaml -> json.

I can spend some time to implement this.

**Comment by borkdude** [comment]
Sounds good!

**Comment by borkdude** [comment]
Released! Thanks @qdzo !

**Comment by qdzo** [comment]
Thank you for the fast release !!!
Already use the new version 😃
