### ISSUE TITLE
--pretty doesn't preserve the order of the keys

### ISSUE THREAD

**Issue by agzam** [borkdude/jet#75]
It seems when using `jet --pretty` on a larger (than just a few items) maps results with keys getting out of order. 

e.g.: use this trivial map with some "lorem ipsum" key/vals

    {:aam       :euismod
     :bellus    :id
     :crat      :donec
     :ditae     :dolor.
     :ehasellus :at
     :fui       :in
     :gigula    :mollis
     :hltricies :mauris
     :iollis    :tincidunt}
    
Notice the keys are sorted. But after running `jet --pretty`:

    {:ehasellus :at,
     :crat :donec,
     :ditae :dolor.,
     :fui :in,
     :bellus :id,
     :hltricies :mauris,
     :iollis :tincidunt,
     :aam :euismod,
     :gigula :mollis}
    
The keys are no longer sorted. Optionally, it would be nice if `--pretty` by default did not add the commas

**Comment by borkdude** [comment]
@agzam Maps aren't sorted by definition in Clojure. You are hitting an implementation detail of Clojure using array maps or hash maps as the backing implementation of a map literal.

I recommend zprint (https://github.com/kkinnear/zprint) or puget (https://github.com/borkdude/puget-cli) for more configurable pretty printing. Currently the pretty printing in jet is done using fipp, but it currently doesn't expose any options. We may switch over to some other pretty printer in the future, haven't thought about this much yet.

**Comment by agzam** [comment]
Of course. The point of adding this issue is not to complain but for mere prosperity. I haven't seen puget-cli, installing it posthaste. Thank you Michiel! I'm gonna close this for now.

**Comment by borkdude** [comment]
@agzam zprint also has a graal native CLI. It uses sci for executing functions from configuration.

**Comment by agzam** [comment]
zprint didn't work for me on Mac:

```
zprint: mach_memory_info: (os/kern) invalid host (try running as root)
```

which makes it difficult for me to run it from Emacs with `<C-u |> - shell-command-on-region`

**Comment by agzam** [comment]
I created an issue https://github.com/kkinnear/zprint/issues/174

**Comment by borkdude** [comment]
@agzam You might be using the wrong `zprint`. There is a binary in macOS called `zprint` too which prints information about kernel zones (try `man zprint`).

**Comment by agzam** [comment]
Urrgh... yes, that was it. I had to rename zprint's executable, so it doesn't have name collusion with BSD zprint.
