### ISSUE TITLE
Maybe cut a new tag?

### ISSUE THREAD

**Issue by dotemacs** [borkdude/jet#79]
Hey @borkdude 

Thanks for adding the short switch options.

Can you please tag the latest master so that it can be picked up by `brew upgrade jet`?
Because it currently sees the `v0.0.13` tag, from August 2020.

Thanks

**Comment by borkdude** [comment]
Yes, I will create a new release.

**Comment by borkdude** [comment]
Done: https://github.com/borkdude/jet/releases/tag/v0.0.14

**Comment by dotemacs** [comment]
Thank you :)
