### ISSUE TITLE
Can `-q` be added for `--query`?

### ISSUE THREAD

**Issue by dotemacs** [borkdude/jet#80]
Is there a reason that `-q` wasn't added for `--query`?

I'd be happy to add it, mostly because it's simpler to type `-q` on the command line instead of `--query`.

Let me know how you feel about it @borkdude 

Thanks

**Comment by borkdude** [comment]
No reason, feel free to add.

**Comment by dotemacs** [comment]
Added https://github.com/borkdude/jet/pull/81, closing
